name: Run automated tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build unit test project
      run: dotnet build tests/Nmd.Tests.Unit --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test tests/Nmd.Tests.Unit --no-restore --verbosity normal

    
